# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vue File Agent
tagline: Every file deserves to be treated equally
email: safrazik@gmail.com
description: Full featured drag & drop enabled Vue file upload component with previews and upload progress
baseurl: "/vue-file-agent" # the subpath of your site, e.g. /blog
url: http://safrazik.github.io/vue-file-agent # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: safrazik
github_username:  safrazik
dist_baseurl: "/vue-file-agent/dist"
activity_feed: true
google_analytics: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - README.md
  - vue.config.js
  - src
  - tests
  - examples
  - the-library

sass:
    sass_dir: website/assets/_scss

theme: jekyll-theme-cayman